# If you have OpenSSL installed, we recommend updating
# the following line to use "https"
source "https://rubygems.org"

gem "middleman", "~>3.2.2"
gem "middleman-livereload"
gem "middleman-imageoptim", "~> 0.1.3"
gem "bourbon"
gem "neat"
gem "middleman-smusher"
gem "middleman-blog"
gem "middleman-deploy"
gem "nokogiri"
gem "slim"
gem "builder"
